eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8000/eureka/
#spring:
#  application:
#    name: consume-distributed
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
   # password:
server:
  port: 8082
feign:
  hystrix:
    enabled: true
